let DisplayData = [
    { text: "YES", row: 1, col: 0 },
    { text: "FIRST", row: 0, col: 1 },
    { text: "DISPLAY", row: 2, col: 1 },
    { text: "OKAY", row: 0, col: 1 },
    { text: "SAYS", row: 2, col: 1 },
    { text: "NOTHING", row: 1, col: 0 },
    { text: " ", row: 2, col: 0 },
    { text: "BLANK", row: 1, col: 1 },
    { text: "NO", row: 2, col: 1 },
    { text: "LED", row: 1, col: 0 },
    { text: "LEAD", row: 2, col: 1 },
    { text: "READ", row: 1, col: 1 },
    { text: "RED", row: 1, col: 1 },
    { text: "REED", row: 2, col: 0 },
    { text: "LEED", row: 2, col: 0 },
    { text: "HOLD ON", row: 2, col: 1 },
    { text: "YOU", row: 1, col: 1 },
    { text: "YOU ARE", row: 2, col: 1 },
    { text: "YOUR", row: 1, col: 1 },
    { text: "YOU'RE", row: 1, col: 1 },
    { text: "UR", row: 0, col: 0 },
    { text: "THERE", row: 2, col: 1 },
    { text: "THEY'RE", row: 2, col: 0 },
    { text: "THEIR", row: 1, col: 1 },
    { text: "THEY ARE", row: 1, col: 1 },
    { text: "SEE", row: 2, col: 1 },
    { text: "C", row: 0, col: 1 },
    { text: "CEE", row: 2, col: 1 }
];

let ButtonText = [
    {text:"READY", buttonList:["YES", "OKAY", "WHAT", "MIDDLE", "LEFT", "PRESS", "RIGHT", "BLANK", "READY", "NO", "FIRST", "UHHH", "NOTHING", "WAIT"]},
    {text:"FIRST", buttonList:["LEFT", "OKAY", "YES", "MIDDLE", "NO", "RIGHT", "NOTHING", "UHHH", "WAIT", "READY", "BLANK", "WHAT", "PRESS", "FIRST"]},
    {text:"NO", buttonList:["BLANK", "UHHH", "WAIT", "FIRST", "WHAT", "READY", "RIGHT", "YES", "NOTHING", "LEFT", "PRESS", "OKAY", "NO", "MIDDLE"]},
    {text:"BLANK", buttonList:["WAIT", "RIGHT", "OKAY", "MIDDLE", "BLANK", "PRESS", "READY", "NOTHING", "NO", "WHAT", "LEFT", "UHHH", "YES", "FIRST"]},
    {text:"NOTHING", buttonList:["UHHH", "RIGHT", "OKAY", "MIDDLE", "YES", "BLANK", "NO", "PRESS", "LEFT", "WHAT", "WAIT", "FIRST", "NOTHING", "READY"]},
    {text:"YES", buttonList:["OKAY", "RIGHT", "UHHH", "MIDDLE", "FIRST", "WHAT", "PRESS", "READY", "NOTHING", "YES", "LEFT", "BLANK", "NO", "WAIT"]},
    {text:"WHAT", buttonList:["UHHH", "WHAT", "LEFT", "NOTHING", "READY", "BLANK", "MIDDLE", "NO", "OKAY", "FIRST", "WAIT", "YES", "PRESS", "RIGHT"]},
    {text:"UHHH", buttonList:["READY", "NOTHING", "LEFT", "WHAT", "OKAY", "YES", "RIGHT", "NO", "PRESS", "BLANK", "UHHH", "MIDDLE", "WAIT", "FIRST"]},
    {text:"LEFT", buttonList:["RIGHT", "LEFT", "FIRST", "NO", "MIDDLE", "YES", "BLANK", "WHAT", "UHHH", "WAIT", "PRESS", "READY", "OKAY", "NOTHING"]},
    {text:"RIGHT", buttonList:["YES", "NOTHING", "READY", "PRESS", "NO", "WAIT", "WHAT", "RIGHT", "MIDDLE", "LEFT", "UHHH", "BLANK", "OKAY", "FIRST"]},
    {text:"MIDDLE", buttonList:["BLANK", "READY", "OKAY", "WHAT", "NOTHING", "PRESS", "NO", "WAIT", "LEFT", "MIDDLE", "RIGHT", "FIRST", "UHHH", "YES"]},
    {text:"OKAY", buttonList:["MIDDLE", "NO", "FIRST", "YES", "UHHH", "NOTHING", "WAIT", "OKAY", "LEFT", "READY", "BLANK", "PRESS", "WHAT", "RIGHT"]},
    {text:"WAIT", buttonList:["UHHH", "NO", "BLANK", "OKAY", "YES", "LEFT", "FIRST", "PRESS", "WHAT", "WAIT", "NOTHING", "READY", "RIGHT", "MIDDLE"]},
    {text:"PRESS", buttonList:["RIGHT", "MIDDLE", "YES", "READY", "PRESS", "OKAY", "NOTHING", "UHHH", "BLANK", "LEFT", "FIRST", "WHAT", "NO", "WAIT"]},
    {text:"YOU", buttonList:["SURE", "YOU ARE", "YOUR", "YOU'RE", "NEXT", "UH HUH", "UR", "HOLD", "WHAT?", "YOU", "UH UH", "LIKE", "DONE", "U"]},
    {text:"YOU ARE", buttonList:["YOUR", "NEXT", "LIKE", "UH HUH", "WHAT?", "DONE", "UH UH", "HOLD", "YOU", "U", "YOU'RE", "SURE", "UR", "YOU ARE"]},
    {text:"YOUR", buttonList:["UH UH", "YOU ARE", "UH HUH", "YOUR", "NEXT", "UR", "SURE", "U", "YOU'RE", "YOU", "WHAT?", "HOLD", "LIKE", "DONE"]},
    {text:"YOU'RE", buttonList:["YOU", "YOU'RE", "UR", "NEXT", "UH UH", "YOU ARE", "U", "YOUR", "WHAT?", "UH HUH", "SURE", "DONE", "LIKE", "HOLD"]},
    {text:"UR", buttonList:["DONE", "U", "UR", "UH HUH", "WHAT?", "SURE", "YOUR", "HOLD", "YOU'RE", "LIKE", "NEXT", "UH UH", "YOU ARE", "YOU"]},
    {text:"U", buttonList:["UH HUH", "SURE", "NEXT", "WHAT?", "YOU'RE", "UR", "UH UH", "DONE", "U", "YOU", "LIKE", "HOLD","YOU ARE", "YOUR"]},
    {text:"UH HUH", buttonList:["UH HUH", "YOUR", "YOU ARE", "YOU", "DONE", "HOLD", "UH UH", "NEXT", "SURE", "LIKE", "YOU'RE", "UR", "U", "WHAT?"]},
    {text:"UH UH", buttonList:["UR", "U", "YOU ARE", "YOU'RE", "NEXT", "UH UH", "DONE", "YOU", "UH HUH", "LIKE", "YOUR", "SURE", "HOLD", "WHAT?"]},
    {text:"WHAT?", buttonList:["YOU", "HOLD", "YOU'RE", "YOUR", "U", "DONE", "UH UH", "LIKE", "YOU ARE", "UH HUH", "UR", "NEXT", "WHAT?", "SURE"]},
    {text:"DONE", buttonList:["SURE", "UH HUH", "NEXT", "WHAT?", "YOUR", "UR", "YOU'RE", "HOLD", "LIKE", "YOU", "U", "YOU ARE", "UH UH", "DONE"]},
    {text:"NEXT", buttonList:["WHAT?", "UH HUH", "UH UH", "YOUR", "HOLD", "SURE", "NEXT", "LIKE", "DONE", "YOU ARE", "UR", "YOU'RE", "U", "YOU"]},
    {text:"HOLD", buttonList:["YOU ARE", "U", "DONE", "UH UH", "YOU", "UR", "SURE", "WHAT?", "YOU'RE", "NEXT", "HOLD", "UH HUH", "YOUR", "LIKE"]},
    {text:"SURE", buttonList:["YOU ARE", "DONE", "LIKE", "YOU'RE", "YOU", "HOLD", "UH HUH", "UR", "SURE", "U", "WHAT?", "NEXT", "YOUR", "UH UH"]},
    {text:"LIKE", buttonList:["YOU'RE", "NEXT", "U", "UR", "HOLD", "DONE", "UH UH", "WHAT?", "UH HUH", "YOU", "LIKE", "SURE", "YOU ARE", "YOUR"]},
];